unit Embedded_GUI_AVR_Default_Fuse_Const;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils;

type
  TDefault_Fuse = array of record
    Name: string;
    Data: array of byte;
  end;

const
  Default_Fuse: TDefault_Fuse = (
    (Name: 'ATtiny9'; Data: ({$FF,lock})),
    (Name: 'ATtiny88'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny87'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny861'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny861A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny85'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny84'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny84A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny841'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny828'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny817'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny816'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny814'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny807'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny806'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny804'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny5'; Data: ({BYTE0,lock})),
    (Name: 'ATtiny4'; Data: ({BYTE0,lock})),
    (Name: 'ATtiny48'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny461'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny461A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny45'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny44'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny44A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny441'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny43U'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny4313'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny417'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny416'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny414'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny412'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny40'; Data: ({BYTE0,lock})),
    (Name: 'ATtiny406'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny404'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny402'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny3217'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny3216'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny3214'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny26'; Data: ({hfuse,lfuse,lock})),
    (Name: 'ATtiny261'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny261A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny25'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny24'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny24A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny2313'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny2313A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny214'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny212'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny20'; Data: ({BYTE0,lock})),
    (Name: 'ATtiny204'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny202'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny167'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny1634'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATtiny1617'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny1616'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny1614'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny1607'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny1606'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny1604'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse4,fuse0,lock})),
    (Name: 'ATtiny15'; Data: ({lfuse,lock})),
    (Name: 'ATtiny13'; Data: ({hfuse,lfuse,lock})),
    (Name: 'ATtiny13A'; Data: ({hfuse,lfuse,lock})),
    (Name: 'ATtiny12'; Data: ({lfuse,lock})),
    (Name: 'ATtiny11'; Data: ({lfuse,lock})),
    (Name: 'ATtiny10'; Data: ({BYTE0,lock})),
    (Name: 'ATtiny104'; Data: ({BYTE0,lock})),
    (Name: 'ATtiny102'; Data: ({BYTE0,lock})),
    (Name: 'ATmega8'; Data: ({hfuse,lfuse,lock})),
    (Name: 'ATmega8U2'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega8HVA'; Data: ({lfuse,lock})),
    (Name: 'ATmega8A'; Data: ({hfuse,lfuse,lock})),
    (Name: 'ATmega88'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega88P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega88PB'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega88PA'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega88A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega8535'; Data: ({hfuse,lfuse,lock})),
    (Name: 'ATmega8515'; Data: ({hfuse,lfuse,lock})),
    (Name: 'ATmega809'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse0,lock})),
    (Name: 'ATmega808'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse0,lock})),
    (Name: 'ATmega64'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega64RFR2'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega64M1'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega64HVE2'; Data: ({lfuse,hfuse,lock})),
    (Name: 'ATmega64C1'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega64A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega649'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega649P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega649A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega6490'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega6490P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega6490A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega645'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega645P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega645A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega6450'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega6450P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega6450A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega644'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega644RFR2'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega644P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega644PA'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega644A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega640'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega48'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega48P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega48PB'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega48PA'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega48A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega4809'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse0,lock})),
    (Name: 'ATmega4808'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse0,lock})),
    (Name: 'ATmega406'; Data: ({hfuse,lfuse,lock})),
    (Name: 'ATmega32'; Data: ({hfuse,lfuse,lock})),
    (Name: 'ATmega32U4'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega32U2'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega32M1'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega32HVB'; Data: ({lfuse,hfuse,lock})),
    (Name: 'ATmega32HVBrevB'; Data: ({lfuse,hfuse,lock})),
    (Name: 'ATmega32C1'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega32A'; Data: ({hfuse,lfuse,lock})),
    (Name: 'ATmega329'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega329P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega329PA'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega329A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega3290'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega3290P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega3290PA'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega3290A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega328'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega328P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega328PB'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega325'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega325P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega325PA'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega325A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega3250'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega3250P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega3250PA'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega3250A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega324P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega324PB'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega324PA'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega324A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega3209'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse0,lock})),
    (Name: 'ATmega3208'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse0,lock})),
    (Name: 'ATmega256RFR2'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega2564RFR2'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega2561'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega2560'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega16'; Data: ({hfuse,lfuse,lock})),
    (Name: 'ATmega16U4'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega16U2'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega16M1'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega16HVB'; Data: ({lfuse,hfuse,lock})),
    (Name: 'ATmega16HVBrevB'; Data: ({lfuse,hfuse,lock})),
    (Name: 'ATmega16HVA'; Data: ({lfuse,lock})),
    (Name: 'ATmega16A'; Data: ({hfuse,lfuse,lock})),
    (Name: 'ATmega169P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega169PA'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega169A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega168'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega168P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega168PB'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega168PA'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega168A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega165P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega165PA'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega165A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega164P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega164PA'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega164A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega162'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega1609'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse0,lock})),
    (Name: 'ATmega1608'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse0,lock})),
    (Name: 'ATmega128'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega128RFR2'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega128RFA1'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega128A'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega1284'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega1284RFR2'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega1284P'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega1281'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'ATmega1280'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90USB82'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90USB647'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90USB646'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90USB162'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90USB1287'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90USB1286'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90PWM81'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90PWM3B'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90PWM316'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90PWM2B'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90PWM216'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90PWM1'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90PWM161'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90CAN64'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90CAN32'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AT90CAN128'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AAAATtiny13'; Data: ({hfuse,lfuse,lock})),
    (Name: 'AAAAATtiny2313A (Kopie)'; Data: ({efuse,hfuse,lfuse,lock})),
    (Name: 'AAAAAATmega4809 (Kopie)'; Data: ({fuse7,fuse1,fuse8,fuse2,fuse5,fuse6,fuse0,lock})),
    (Name: 'Test0'; Data: ($00, $00, $00, $00)),
    (Name: 'Test1'; Data: ($00)));

implementation

end.

