language: c

jobs:
  include:
    ### cross builds on AMD64 ###

    - os: linux
      dist: focal
      env: BADGE=linux-mingw-64
      name: linux-mingw
      compiler: gcc-10
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages:
            ["gcc-10", "libusb-1.0.0-dev", "libgtk-3-dev", "rpm", "mingw-w64"]

    - os: linux
      dist: focal
      env: BADGE=linux-mingw-32
      name: linux-mingw
      compiler: gcc-10
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages:
            ["gcc-10", "libusb-1.0.0-dev", "libgtk-3-dev", "rpm", "mingw-w64"]

script:
  - git fetch --tags
  - printenv
  - cmake --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis.sh; fi
